### PR TITLE
[In Progress] Bahasa Indonesia - Web Accessibility Perspectives Videos: Explore the Impact and Benefits for Everyone

### PR DESCRIPTION
**Pull request by frirasyidi**
Add Bahasa Indonesia translation for:
- index.md
- captions.md + cc
- contrast.md + cc
- controls.md + cc
- customizable.md + cc
- keyboard.md + cc
- layout.md + cc
- notifications.md + cc
- speech.md + cc
- understandable.md + cc
- voice.md + cc
- cc compilation

### CODE REVIEW

**Comment by frirasyidi** [comment]
@remibetin should I add language code for links in the Learn More section as well? I noticed that this is not done in the French translation, but the preview suggest that it does not directly link to the relevant translation page.

**Comment by remibetin** [comment]
@frirasyidi 

> @remibetin should I add language code for links in the Learn More section as well?

No. The language code will be automatically added when these pages are translated into Indonesian. In the meantime, "(dalam Bahasa Inggris)" is automatically added at the end of the link text to specify these resources have not been translated (yet!)

We only ask you to add the language code to links in "Perspectives Videos" section because they are coded differently.

**Comment by frirasyidi** [comment]
@remibetin I would like to notify you that there's content differences in the transcript in ```_perspective-videos/voice.md```, ```_perspective-videos/cc/en/voice.en.vtt``` and ```_perspective-videos/cc/en/voice_ad.en.vtt```.

As of now, I'm adjusting the translation according to each file's content. Let me know if there's any adjustment that I need to make.

**Comment by frirasyidi** [comment]
@remibetin I noticed that the link to caption caption file in the main page is redirecting to English in Bahasa Indonesia page. And it links to some ```.../compilations.srt``` instead of the ```.../cc/compilation.id.vtt``` file.

I don't think I missed any step from the ```Translation Notes```. Will this be automatically generated from the ```.../cc/compilation.id.vtt``` or something needs to be done from my side?

**Comment by remibetin** [comment]
@frirasyidi 

> I noticed that the link to caption caption file in the main page is redirecting to English in Bahasa Indonesia page. And it links to some .../compilations.srt instead of the .../cc/compilation.id.vtt file.

I need to check something; I will get back to you on this. For now, keep the existing link to .../compilations.srt

> Another thing is that the video does not automatically use Bahasa Indonesia as its default caption.

Indeed, I opened an issue some weeks ago (https://github.com/w3c/wai-video-standards-and-benefits/issues/118) and am in the process of fixing this.

> I noticed that the French translation did not attempt any changes to make French its default.

We are currently simplifying the way VTT files are managed: I will update the documentation next week. 

Do not mind about the video player include for now: you can focus on the VTT files and the page content for now, and I will directly commit the necessary changes in your PR when ready (likely next week).

**Comment by frirasyidi** [comment]
@remibetin per our communication via email, this document status is changed back to [In Progress], waiting for check from your side before ready to review.

**Comment by remibetin** [comment]
This PR has been split into two:
– Resource update: https://github.com/w3c/wai-perspective-videos/pull/67
– VTT update: https://github.com/w3c/wai-website-data/pull/115

**Pull request closed without merging**
