### PR TITLE
[Ready for Review] Create Spanish translation of Web Accessibility Perspectives Videos: …

### PR DESCRIPTION
**Pull request by visanju**
First translation of Web Accessibility Perspectives Videos: Explore the Impact and Benefits for Everyone

Resolves https://github.com/w3c/wai-translations/issues/185

### CODE REVIEW

**Comment by visanju** [comment]
I'm not sure if this behaviour is correct or means that I made a mistake:
When checking the preview:
https://app.netlify.com/sites/wai-perspective-videos/deploys/6561c92ae45fc70008675d3c
I have to manually add /es at the end of the URL to preview my changes. Text is in Spanish but the page has no styles
image

**Comment by remibetin** [comment]
Hi @visanju,

Thank you so much for volunteering to translate this resource. If you have not already, could you please [open an Issue](https://github.com/w3c/wai-translations/issues/new/choose) to declare your intent? I will then send you specific guidance to translate this set of resources.

Concerning the issue you are facing, it is probably because `index.es.md` must be located in the `content/` folder. Can you try it and confirm it resolves the issue?

**Comment by remibetin** [comment]
Hi @visanju 

My bad, the correct folder was `_perspective-videos`. I have applied the fix and the preview is working fine now! 

See https://deploy-preview-66--wai-perspective-videos.netlify.app/perspective-videos/es

**Comment by remibetin** [comment]
Hi @visanju,

Please note that this content has been moved to `wai-website` repository. I have therefore re-created your PR at https://github.com/w3c/wai-website/pull/830

Are you planning on translating other parts of this resource? Let me know how I can help.

Thanks!

**Pull request closed without merging**
