### PR TITLE
WCAG 2.1 update

### PR DESCRIPTION
**Pull request by nitedog**
Added considerations for 1.4.11 Non-Text Contrast

### CODE REVIEW

**Comment by yatil** [comment]
I think we can just merge this change, right?

**Comment by slhenry** [comment]
Will do later as a batch.

**Review by shawna-slh — CHANGES_REQUESTED** [review]
Approved.
Please update the footer to the date when you publish it. Thanks!

**Comment by remibetin** [comment]
@shawna-slh @nitedog Updated and published today, see https://www.w3.org/WAI/perspective-videos/contrast/

**Pull request merged**
